
export struct VaultEntryData {
    id: string,
    title: string,
    username: string,
    url: string,
    icon_text: string,
    deleted: bool,
    folder: string,
    icon: image,
    has_icon: bool,
    totp_code: string,
    has_totp: bool,
    entry_type: string, // "account" or "totp"
    notes: string,
}

export struct GeneratorSettings {
    length: int,
    include_uppercase: bool,
    include_lowercase: bool,
    include_numbers: bool,
    include_symbols: bool,
}
